CREATE TABLE WORKQUEUE (
    INSTANCE VARCHAR(32),
    TYPE VARCHAR(32),
    KEY VARCHAR(256),
    TS TIMESTAMP WITH TIME ZONE,
    GEN BIGINT NOT NULL DEFAULT 0,

    PRIMARY KEY (INSTANCE, TYPE, KEY)
);