kind: Kafka
apiVersion: kafka.strimzi.io/v1beta1
metadata:
  name: kafka-eventing
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: '2.7'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - name: plain
        tls: false
        port: 9092
        type: internal
      - name: tls
        tls: true
        port: 9093
        type: internal
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
    version: 2.7.0
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
