= The Things Network integration

Drogue IoT Cloud has can integrate with https://www.thethingsnetwork.org/[The Things Network] (TTN).

Applications and devices managed in the Drogue IoT device registry can be synced to the TTN system. This
includes automatically connecting both systems using a Drogue cloud gateway device, to receive messages
from LoRa devices through the TTN system.

The integration is meant to be configured on a per-application level, so that normal users of Drogue Cloud
can configure their own integration, using their own TTN account. There is no system-wide synchronization.

NOTE: The integration works with V3 of the TTN API. Earlier versions are not supported.

The integration currently supports:

* Creating applications in The Things Network.
  ** Creating a gateway device in Drogue Cloud.
  ** Configuring the credentials for this gateway device using a randomized password-
  ** Creating an application instance on the TTN side.
  ** Creating a webhook for this application, connecting the TTN side with Drogue Cloud, using the created gateway device.
* Creating devices in The Things Network.
  ** Authorizing the TTN gateway device in Drogue Cloud for this device
  ** Creating the device on the TTN side
* Cleaning up when resources get deleted

[WARNING]
.Deleting applications
====
Deleting an application in Drogue Cloud, or disabling the TTN integration for a Drogue Cloud application,
will also delete the application in TTN.

However, The Things Network only soft deletes applications. The name of the application is still blocked
from further use after the deletion. This means that you cannot simply re-create an application with
the same name. Drogue Cloud allows you to override the application name on the TTN side, however you
should consider twice before actually trigger a delete.
====
