= Services

The Drogue IoT deployment is based on multiple internal and external services. This section gives an overview on
the most important ones.

== Infrastructure

Infrastructure services are not IoT specific, still required for a deployment.

=== Single sign-on

A single sign-on (SSO) service, used to authenticate users for interacting with the other Drogue IoT services.

NOTE: The single sign-on service is not used for authenticating devices.

=== Device authentication service

The device authentication service allows the protocol endpoints to authentication devices, based on the data
stored in the <<Device registry>>.

=== User authorization service

The user authorization service evaluates if a user, as authenticated by the sigle sign-on service, has access to a
resource.

== Management

=== API

The common backend API.

=== Device registry

A registry, storing information about applications and devices, used by the system.

This store is also used by the <<Device authentication service>> to authenticate and authorize devices.

=== Web Console

A general purpose web console, with functionality specific to Drogue IoT.

== Endpoints

Protocol endpoints, used for devices to communicate with the system.

=== HTTP endpoint

A general purpose HTTP endpoint.

It provides API compatible with:

* Drogue IoT
* The Things Network
* Eclipse Hono

=== MQTT endpoint

A general purpose MQTT endpoint, providing a Drogue IoT specific API.

== Integrations

Integration services allow cloud side applications to interface with Drogue IoT, in order to communicate with devices.

=== MQTT Integration

The MQTT integration is a multi-application, push based integration, which allows to use MQTT v3.1.1 and v5 for
receiving events coming from devices.

It provides events in the MQTT cloud events format 1.0, in both _structured_ and _binary_ mode.

== Additional services

These services may be part of a Drogue IoT deployment. However, they are not considered core functionality, but
additional services, to showcase Drogue IoT functionality.

NOTE: Depending on a specific Drogue IoT deployment, these services may or may not be present in a system.

=== InfluxDB

Used as an example time series database. Recording temperate measurements, extracted by a Knative serverless function.

=== Grafana

Provides dashboards for showing data from the InfluxDB instance.

This service is integrated with the internal single sign-on.

=== Eclipse Ditto

Acts as digital twin example. Can be set up to normalize device specific payload, using an Eclipse Vorto instance
through a Knative serverless function.

This service is integrated with the internal single sign-on.
