[package]
name = "drogue-cloud-test-common"
version = "0.8.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
testcontainers = "0.12"
deadpool = "0.7"
deadpool-postgres = "0.7"
walkdir = "2"

serde = "1"
serde_json = "1"
