[package]
name = "drogue-cloud-test-common"
version = "0.9.0"
authors = ["Jens Reimann <jreimann@redhat.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
async-std = "1"
async-trait = "0.1"
cloudevents-sdk = "0.5"
deadpool = "0.7"
deadpool-postgres = "0.7"
log = "0.4"
serde = "1"
serde_json = "1"
testcontainers = "0.12"
walkdir = "2"

drogue-cloud-service-api = { path = "../service-api" }
drogue-cloud-service-common = { path = "../service-common" }

drogue-cloud-endpoint-common = { path = "../endpoint-common", optional = true }

[dev-dependencies]
tokio = "1"
drogue-client = "0.10"

[features]
default = []
actix = [ "drogue-cloud-service-api/actix" ]
