ALTER TABLE applications
    DROP COLUMN REVISION
;

ALTER TABLE devices
    DROP COLUMN REVISION
;

ALTER TABLE outbox
    RENAME COLUMN REVISION TO GENERATION;

ALTER TABLE WORKQUEUE
    RENAME COLUMN REV TO GEN;
