BEGIN;

-- applications

ALTER TABLE applications
    ADD COLUMN REVISION BIGINT NOT NULL DEFAULT 0
;

UPDATE applications SET REVISION = GENERATION;

ALTER TABLE applications
    ALTER COLUMN REVISION DROP DEFAULT
;

-- devices

ALTER TABLE devices
    ADD COLUMN REVISION BIGINT NOT NULL DEFAULT 0
;

UPDATE devices SET REVISION = GENERATION;

ALTER TABLE devices
    ALTER COLUMN REVISION DROP DEFAULT
;

-- commit

COMMIT;

ALTER TABLE outbox
    RENAME COLUMN GENERATION TO REVISION;

ALTER TABLE WORKQUEUE
    RENAME COLUMN GEN TO REV;
