= Noteworthy services

Drogue Cloud consists of multiple internal and external services, as explained in this chapter. The following sub-sections
list a few of the core services, considered interfacing points for users of Drogue Cloud.

== Device Registry

=== Management API

The management access to the device registry.

=== Operators

Acting on device change events, operators will reconcile the desired state of applications and devices, with internal
or external services.

==== Topic operator

The topic operator creates Kafka topics as required by the applications.

==== The Things Network operator

The Things Network operator (TTN operator) sets up a connection between Drogue Cloud and a TTN V3  instance. It will
also synchronize devices from Drogue Cloud to TTN.

== Endpoints

Protocol endpoints, used for devices to communicate with the system.

=== CoAP endpoint

A general purpose CoAP endpoint, providing a Drogue IoT specific API.

=== HTTP endpoint

A general purpose HTTP endpoint.

It provides API compatible with:

* Drogue IoT
* The Things Network
* Eclipse Hono

=== MQTT endpoint

A general purpose MQTT endpoint, providing a Drogue IoT specific API.

=== Command endpoint

A drop-off point, with an HTTP API, for cloud-to-device messages.

== Integrations

Integration services allow cloud side applications to interface with Drogue IoT, in order to communicate with devices.

=== MQTT Integration

The MQTT integration is a multi-application, push based integration, which allows to use MQTT v3.1.1 and v5 for
receiving events coming from devices.

It provides events in the MQTT cloud events format 1.0, in both _structured_ and _binary_ mode.
