# use in combination with the openshift.yaml file

global:
  drogueCloud:
    keycloak:
      insecure: true

drogueCloudCore:

  console:
    localCertificates: true

  services:
    console:
      ingress:
        insecure: true
        port: 80

    api:
      ingress:
        insecure: true
        port: 80

    sso:
      ingress:
        insecure: true
        port: 80

drogueCloudExamples:

  grafana:
    ingress:
      insecure: true
