
# Ports might seem a bit off, but they must be in the range of 30000-32767

drogueCloudCore:
  endpoints:
    coap:
      ingress:
        port: 30003
    mqtt:
      ingress:
        port: 30001
    mqttWs:
      ingress:
        port: 30005
    http:
      ingress:
        port: 30443

  integrations:
    mqtt:
      ingress:
        port: 30002
    mqttWs:
      ingress:
        port: 30006
    websocket:
      insecure: true
      ingress:
        port: 30004

  console:
    localCertificates: true

  services:
    sso:
      ingress:
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          nginx.ingress.kubernetes.io/server-snippet: |2-
                              location ~* "^/auth/realms/master/metrics" {
                                  return 301 /auth/realms/master;
                              }
