
# Ports might seem a bit off, but they must be in the range of 30000-32767

endpoints:
  coap:
    ingress:
      port: 30003
  mqtt:
    ingress:
      port: 30001
  http:
    ingress:
      port: 30443

integrations:
  mqtt:
    ingress:
      port: 30002
  websocket:
    insecure: true
    ingress:
      port: 30004