
# Ports might seem a bit off, but they must be in the range of 30000-32767

global:
  drogueCloud:
    keycloak:
      insecure: true

drogueCloudCore:
  endpoints:
    coap:
      ingress:
        port: 30003
    mqtt:
      ingress:
        port: 30001
    mqttWs:
      ingress:
        port: 30005
    mqttWsBrowser:
      ingress:
        port: 30007
    http:
      ingress:
        port: 30443

  integrations:
    mqtt:
      ingress:
        port: 30002
    mqttWs:
      ingress:
        port: 30006
    mqttWsBrowser:
      ingress:
        port: 30008
    websocket:
      ingress:
        port: 30004

  console:
    localCertificates: true

drogueCloudExamples:

  grafana:
    ingress:
      insecure: true
