= Prepare the cluster

First we need to prepare the cluster.

== Minikube

[source,bash]
----
minikube start --cpus 4 --memory 16384 --disk-size 20gb --addons ingress
----

Once the cluster is up and running, you need the start the load balancer tunnel in a new terminal,
as this command must be running until you shut down your cluster, or the tunnel.

[source,bash]
----
minikube tunnel
----

== Kind

Creating a new cluster with Kind requires to execute the following command:

[source,bash]
----
kind create cluster --config=deploy/kind/cluster-config.yaml
----

[NOTE]
.Ingress controller required
====
The deployment requires a Kubernetes ingress controller to be deployed. When using Kind, the deployment script will
automatically deploy the https://kubernetes.github.io/ingress-nginx/[NGINX Ingress Controller], but you still need
to export the ports as shown above.
====

== Other

For any other cluster:

* You need to have a working context for `kubectl` (e.g. `oc login`).
* You will need to be able to create new namespaces, being _admin_ helps.
* You need a working Ingress Controller.  For OpenShift, you can use `Routes`.
* You need some kind of `LoadBalancer` support. For OpenShift, you can use `Routes`.
* You must have `PersistentVolumes` available to bind to.
