= Deploying from the repository

Instead of running the installer, which installs a released version of Drogue Cloud, you can also directly from the
repository, using `:latest` images instead. The same way, you can also deploy your custom-built images.

[IMPORTANT]
.`main` and tagged versions
====
Deploying from the repository implies that you install `latest` or `main`. Even when you check out a tag or branch from
the repository, this will always install `latest`. If you want to install a tagged version, use the installer.
====

== Additional pre-requisites

Additionally, you will need to:

* `git`
* Clone the `drogue-cloud` repository

== Deploy standard images

Installing Drogue Cloud, using the standard images, can be done by calling the makefile target `deploy`:

[source,bash]
----
make deploy
----

== Deploy custom images

If you built custom images, and pushed them to a container repository, you can deploy them using the following command:

[source,bash]
----
make CONTAINER_REGISTRY=quay.io/my-repo build images
----

You can install them using:

[source,bash]
----
make CONTAINER_REGISTRY=quay.io/my-repo deploy
----

== Using the installer script for development

The makefile actually uses the installer script `scripts/drgadm` internally. It only passes in the right arguments,
so that the installer will install images from a different registry, or use a different tag.

NOTE: By default, the installer scripts, even on the main branch, will install a tagged version. Sometimes tagged
versions are not yet available on the container registry, and thus, the installation may fail. It is therefore
recommended to install "latest" images using the `make deploy` command.
