= Installer script

Most of the deployment of Drogue Cloud uses `kustomize` as part of `kubectl`. However, we do require a few steps
before and after the deployment. Installing dependencies on the cluster and setting URLs afterwards.

For this we have a _magic_ installer script, that does everything for you. It is suited for an easy start on a
local test cluster.

== Download the installer package

The installer package is part of the GitHub release record: https://github.com/drogue-iot/drogue-cloud/releases/latest

There is one package for each type of Kubernetes cluster:

* `install-minikube` – For using with Minikube
* `install-kind` – For using with Kind
* `install-openshift` – For using with OpenShift

Download the package, matching the cluster you plan to use.

== Unpacking

Unzip the package and change into the folder extracted from the archive.

== What to expect

The installer will create a new instance of Drogue Cloud on the cluster you are currently logged in to.

By default, this includes:

* Installing Knative
* Installing Strimzi
* Creating a Kafka cluster
* Installing the Keycloak operator
* Create a custom CA for the endpoints

If you want to install those dependencies manually, for example using OLM, you can opt-out of the installation
(see below).

== Running the installer

Run the installer script `./script/drogue.sh`, adding the options appropriate for your setup.

You can use the environment variable `CLUSTER` to define which cluster type you have.

[NOTE]
.Default cluster type
====
By default, the cluster type will be `minikube` for the script in the repository. For the installers, this default
value will be changed to the installer type you downloaded. You can still override the default, using:

[source,shell]
----
env CLUSTER=kind ./script/drogue.sh
----

====

== Additional installer options

Most options are controlled by using environment variables. You can set them by prefixing the
call to the installation script, using `env` and the variable assignment:

[source,shell]
----
env CLUSTER=kind INSTALL_DEPS=false ./script/drogue.sh
----

=== Skip the dependency installation

If you want to install the dependencies (like Strimzi, KNative) yourself, you can opt out of installing the
dependencies.

|===
|Variable Name | Default value | Description

| `INSTALL_DEPS`
| `true`
| Control the installation of all dependencies.

| `INSTALL_KNATIVE`
| `$\{INSTALL_DEPS}`
| Control the installation of the Knative stack.

| `INSTALL_KEYCLOAK_OPERATOR`
| `$\{INSTALL_DEPS}`
| Control the installation of the Keycloak operator.

|===

=== Change the target namespace

You can change the namespace where of the Drogue Cloud components get installed using the variable `DROGUE_NS`. The
default is `drogue-iot`.

NOTE: Currently, you can only change the namespace of the Drogue Cloud installation. The namespaces of Knative,
Strimzi, are currently not configurable.

=== Provide custom TLS certificates

By default, the installer script will create a custom certificate authority. However, if you already have a key and
certificate, you can instruct the installer to use these. There are two options to achieve this.

==== Manually create the TLS secrets

The installer will check if the secrets `http-endpoint-tls` and `mqtt-endpoint-tls` exist. If they don't it will
create them either using provided or generated key and certificate material.

If you manually create these TLS secrets, using those names, *before* running the installer, it will not override
these existing secrets.

==== Using local key and certificate files

You can set the environment variable `TLS_KEY` and `TLS_CRT`, pointing them to PEM encoded key and certificate.

== Re-running the installer

Should something go wrong, it should be possible to just re-run the installer script. That should simply set the
_desired state_ again, and Kubernetes should reconcile accordingly. In most of the cases, this works just fine.

== Status information

After the installer script has run, it will show some information on how you can connect to the system and
give some example commands to try out.
