[package]
name = "drogue-cloud-websocket-integration"
version = "0.6.0"
authors = ["Jb Trystram <jbtrystram@redhat.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
anyhow = "1"

actix = { version = "0.12.0"}
actix-http = "=3.0.0-beta.8"
actix-web = "=4.0.0-beta.8"
actix-web-actors = "=4.0.0-beta.6"
actix-web-httpauth = "=0.6.0-beta.2"

dotenv = "0.15"

awc = "2"
log = "0.4"
env_logger = "0.8.4"
futures = "0.3.1"
bytes = "0.5.3"

uuid = { version = "0.8", features = ["v4", "serde"] }
reqwest = "0.11"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

url = "2"

drogue-client = "0.7.1"
drogue-cloud-service-common = { path = "../service-common" }
drogue-cloud-integration-common = { path = "../integration-common", features = ["actix-web"] }
drogue-cloud-service-api = { path = "../service-api" }
