[package]
name = "drogue-cloud-websocket-integration"
description = "Websocket integration"
version = "0.11.0"
authors = ["Jb Trystram <jbtrystram@redhat.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
actix = "0.13.0"
actix-web-actors = "4"
anyhow = "1"
chrono = "0.4"
dotenv = "0.15"
drogue-client = "0.11"
env_logger = "0.9"
futures = "0.3.1"
lazy_static = "1.4.0"
log = "0.4"
prometheus = { version = "^0.13", default-features = false }
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = "1"
url = "2"
uuid = { version = "1", features = ["v4", "serde"] }

drogue-cloud-integration-common = { path = "../integration-common" }
drogue-cloud-service-api = { path = "../service-api" }
drogue-cloud-service-common = { path = "../service-common" }
