images:
  - name: ghcr.io/drogue-iot/authentication-service
    newname: REPLACE-ORG/authentication-service
    newTag: REPLACE-TAG
  - name: ghcr.io/drogue-iot/command-endpoint
    newname: REPLACE-ORG/command-endpoint
    newTag: REPLACE-TAG
  - name: ghcr.io/drogue-iot/console-backend
    newname: REPLACE-ORG/console-backend
    newTag: REPLACE-TAG
  - name: ghcr.io/drogue-iot/database-migration
    newname: REPLACE-ORG/database-migration
    newTag: REPLACE-TAG
  - name: ghcr.io/drogue-iot/device-management-service
    newname: REPLACE-ORG/device-management-service
    newTag: REPLACE-TAG
  - name: ghcr.io/drogue-iot/http-endpoint
    newname: REPLACE-ORG/http-endpoint
    newTag: REPLACE-TAG
  - name: ghcr.io/drogue-iot/mqtt-endpoint
    newname: REPLACE-ORG/mqtt-endpoint
    newTag: REPLACE-TAG

# https://github.com/kubernetes-sigs/kustomize/issues/1493
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/patchMultipleObjects.md
patches:
  - path: image_pull_policy.yaml
    target:
      labelSelector: image-source=build

# not supported in kubectl -k
# https://github.com/kubernetes-sigs/kustomize/issues/1373#issuecomment-618439078
# this works but need to be done after the deployment
# kubectl get deployments -n drogue-iot -l image-source=build
